// ===================================
// Main.cpp file generated by OptFrame
// Project EFP
// ===================================
#include <stdlib.h>
#include <math.h>
#include <iostream>
#include "./cplexMOPoolSearch.hpp"
#include "./readParetoSets.hpp"
#include "./OptFrame/Loader.hpp"

using namespace std;
using namespace optframe;

void fillVectorWithAllCombinations(vector<vector<double> >& values, vector<vector<double> >& combinations)
{
	vector<int> vIndex(values.size(), 0);
	bool exitWhile = true;
	do
	{
		int nObj = values.size();

		for (int i = 0; i < values[0].size(); i++)
		{
			vector<double> coef(nObj);
			for (int o = 0; o < nObj; o++)
				coef[o] = values[o][vIndex[o]];

			combinations.push_back(coef);
			vIndex[0]++;
		}
		vIndex[0] = 0;

//		cout << combinations << endl;
//		cout << index << endl;
//		getchar();

		for (int o = 1; o < nObj; o++)
		{

			if (vIndex[o] < (values[o].size() - 1))
			{
				vIndex[o]++;
				o = nObj;
				break;
			}
			else
			{
				vIndex[o] = 0;

				if (o == (nObj - 1))
					exitWhile = false;
			}
		}

	} while (exitWhile);

}

int main(int argc, char **argv)
{
	int nOfArguments = 4;
	if (argc != (1 + nOfArguments))
	{
		cout << "Parametros incorretos!" << endl;
		cout << "Os parametros esperados sao: \n"
				"1 - instancia \n"
				"2 - MIP START\n"
				"3 - NInterval\n"
				"4 - time limit\n" << endl;
		exit(1);
	}
	const char* instancia = argv[1];
	bool mipStart = atoi(argv[2]);
	int tLim = atoi(argv[3]);
	int nIntervalsCoef = atoi(argv[4]);
	string filename = instancia;
	cout << "filename = " << filename << endl;
	cout << "mipStart = " << mipStart << endl;
	cout << "tLim = " << tLim << endl;
	cout << "nIntervalsCoef(optinal) = " << nIntervalsCoef << endl;

	RandGenMersenneTwister rg;
	long seed = time(NULL);
	seed = 2;
	cout << "seed = " << seed << endl;
	srand(seed);
	rg.setSeed(seed);

	//	readParetoSets rPS;
	//	rPS.exec(filename, mipStart, nIntervalsCoef, tLim);

	//	mModel.analyzeParetoFronts("./ResultadosFronteiras/ParetoFrontInputbWCMNExec27TLim10-bestMIPStart", 68, "./ResultadosFronteiras/ParetoFrontInputbWCMNExec27TLim10", 44);
	//	getchar();

	cplexMOPoolSearch mModel(rg);
	int nOptObj = 7;
	int nCriteria = 0;

	//================================
	//Generating objective functions weights with pre-defined vector of lambda values
	vector<vector<double> > vPossibleCoefs(nOptObj);
	vPossibleCoefs[0] =
	{	1, 10};
	vPossibleCoefs[1] =
	{	0.1,1};
	vPossibleCoefs[2] =
	{	1, 10};
	vPossibleCoefs[3] =
	{	1};
	vPossibleCoefs[4] =
	{	0.01, 0.1};
	vPossibleCoefs[5] =
	{	1, 10};
	vPossibleCoefs[6] =
	{	1, 10};
	//================================

	vector<vector<double> > vMILPCoefs;
	fillVectorWithAllCombinations(vPossibleCoefs, vMILPCoefs);
	cout << vMILPCoefs << endl;
	int maxTriesWithTLimUntilFirstFeasible = 10; //max number of times it will optimize with tLim until finding the First Feasible

	mModel.exec(filename, mipStart, vMILPCoefs, tLim, nOptObj, nCriteria, maxTriesWithTLimUntilFirstFeasible);

	cout << "Main finished com sucesso!" << endl;
}
